[package]
name = "clone"
version = "0.1.0"
authors = ["Milesq <wmilosz88@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.7.1"
serde_json = "1.0.60"
isahc = "0.9.14"
dirs = "3.0.1"
bincode = "1.3.1"
