[package]
name = "clone"
version = "0.1.0"
authors = ["Milesq <wmilosz88@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.6.2"
serde_json = "1.0.59"
isahc = "0.9.10"
dirs = "3.0.1"
bincode = "1.3.1"
