[package]
name = "clone"
version = "0.1.0"
authors = ["Milesq <wmilosz88@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.6.2"
serde_json = "1.0.53"
isahc = "0.9.3"
dirs = "2.0.2"
bincode = "1.2.1"
