[package]
name = "clone"
version = "0.1.0"
authors = ["Milesq <wmilosz88@gmail.com>"]
edition = "2018"

[dependencies]
gql = { path = "./gql" }
dialoguer = "0.9.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
dirs = "4.0.0"
bincode = "1.3.1"
