query($login: String!, $after: String) {
  user(login: $login) {
    repositories(first: 50, after: $after, isFork: false) {
      nodes {
        name
      }

      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
