query ($login: String!, $after: String) {
  user(login: $login) {
    repositories(
      first: 50
      after: $after
      isFork: false
      orderBy: { field: NAME, direction: ASC }
    ) {
      nodes {
        name
      }

      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
